// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxfSuh0S8hucjq9I5h4x3XkcFWr2rM0K4',
    appId: '1:125721940800:web:bee682661f3ec356b5a0a5',
    messagingSenderId: '125721940800',
    projectId: 'volt-app-f8b52',
    authDomain: 'volt-app-f8b52.firebaseapp.com',
    storageBucket: 'volt-app-f8b52.appspot.com',
    measurementId: 'G-QN7TEEKQG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6LP0OF6VBych368d4ljPuJo7Qi364baE',
    appId: '1:125721940800:android:c2375705594b7223b5a0a5',
    messagingSenderId: '125721940800',
    projectId: 'volt-app-f8b52',
    storageBucket: 'volt-app-f8b52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFtNofIJIQy1ef2imal83uvrXn99Dg9hg',
    appId: '1:125721940800:ios:1ab57c9aa0e2d0c5b5a0a5',
    messagingSenderId: '125721940800',
    projectId: 'volt-app-f8b52',
    storageBucket: 'volt-app-f8b52.appspot.com',
    iosBundleId: 'com.example.showcaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFtNofIJIQy1ef2imal83uvrXn99Dg9hg',
    appId: '1:125721940800:ios:7f2dd7598cf44616b5a0a5',
    messagingSenderId: '125721940800',
    projectId: 'volt-app-f8b52',
    storageBucket: 'volt-app-f8b52.appspot.com',
    iosBundleId: 'com.example.showcaseApp.RunnerTests',
  );
}
